spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    cluster:
      nodes:
        - 172.17.0.2:6479
        - 172.17.0.3:6379
        - 172.17.0.4:6379
    password:
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
server:
  port: 8000

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:Mapper/*Mapper.xml
  type-aliases-package: com.zero.qinqiong.Entity